# Generated by Django 4.2.16 on 2025-04-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
    ]
